### ISSUE TITLE
Option to not separate legacy styles

### ISSUE THREAD

**Issue by RinkAttendant6** [Mika-/grunt-google-fonts#10]
Is it possible to generate one CSS file instead of separate WOFF2 and legacy stylesheets?

I'd stick to 0.4.0 but there's a bug in the generated output that indicates WOFF2 as `format('woff')` which causes issues in IE9-11 (and probably Edge 13).

**Comment by Mika-** [comment]
Google split woff2 versions by the subset using ´unicode-range´ property. At the same time they started serving woff version to woff2 capable browsers without complete range support, resulting woff being loaded as woff2.

Unicode-range allows automatic loading of just the needed subset files. As only actually needed characters and font data is loaded, resulting much smaller payload and all the files being loaded in paraller.

Downside having range specification is that old combined files can't be used in same font-face declarations as using multiple declarations results unneeded versions being downloaded.

Best way to get support for maximum amount of browsers is just to leave woff2 out for now or to use javascript to load the proper css file. As IE conditional comments are no longer supported all other ways would require server side approach.

**Comment by RinkAttendant6** [comment]
Good to know, I'll change `woff2` to `false` for the time being as the project I'm working on still needs to support IE 11+.
Thank you!
