### ISSUE TITLE
bump grunt dependancy version

### ISSUE THREAD

**Issue by KristiyanHristov** [Mika-/grunt-google-fonts#6]
grunt is currently at v1.0.1. It will be great if you can update the dependency.

**Comment by Mika-** [comment]
I'm using grunt 1.0.1 and haven't encountered any problems. Peerdepency is grunt >=0.4.0

**Comment by KristiyanHristov** [comment]
This answers my question/confusion. Tnx
http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
