### ISSUE TITLE
Use HTTPS for downloading Google fonts

### ISSUE THREAD

**Issue by RinkAttendant6** [Mika-/grunt-google-fonts#8]
Is it possible to use https://fonts.googleapis.com instead of HTTP when downloading the files?
https://github.com/Mika-/grunt-google-fonts/blob/master/tasks/index.js#L307

**Comment by Mika-** [comment]
That's the way it should be. Looks like the https upgrade was completely forgotten when we switched to request. I'm going to do a bigger maintenance release next weekend.
